---

language: python

python: 2.7

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python software-properties-common

install:
  - sudo add-apt-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install ansible python-httplib2 python-jinja2 python-paramiko python-six python-yaml
  - ansible-galaxy install -r tests/roles.yml

script:
  - ansible-playbook tests/test.yml -i tests/hosts --syntax-check
  - ansible-playbook tests/test.yml -i tests/hosts --connection=local --sudo
  - ansible-playbook tests/test.yml -i tests/hosts --connection=local --sudo | grep -q 'failed=0' && exit 0 || exit 1
